service: howmanylines
frameworkVersion: '2 || 3'

plugins:
  - serverless-offline

custom:
  serverless-offline:
    noPrependStageInUrl: true
    
provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  region: us-east-1

functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'
