name: howmanylines
description: HowManyLines script collection to run on Github Actions
version: 0.1.0
homepage: https://github.com/LaksCastro/how-many-lines

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  http: ^0.13.4
  path: ^1.8.1

dev_dependencies:
  lint: ^1.0.0
  test: ">=1.15.0 <2.0.0"