name: Build README.md
on:
  issues:
    types: [opened, edited, deleted, reopened, labeled, unlabeled]

jobs:
  build-readme:
    runs-on: ubuntu-latest
    steps:
      # Ignore normal issue events
      - name: Exit if is not a pool issue
        if: "contains(github.event.issue.labels.*.name, 'u: pool')"
        run: exit 0

      # Clone and setup local repository
      - uses: actions/checkout@v1

      # Setup Java
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "8"

      # Build markdown and update the `README.md`
      - name: Build README.md Job
        env:
          GITHUB_REPO_TOKEN: ${{ github.token }}
          REPOSITORY: ${{ github.repository }}
        run: cd actions && bash ./gradlew run -P JOB=GenerateMarkdownTable
