name: Build README.md
on:
  workflow_dispatch

jobs:
  build-readme:
    runs-on: ubuntu-latest
    steps:
      # Clone and setup local repository
      - uses: actions/checkout@v1

      # Setup Java
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "8"

      # Build markdown and update the `README.md`
      - name: Build README.md Job
        env:
          GITHUB_REPO_TOKEN: ${{ github.token }}
          REPOSITORY: ${{ github.repository }}
        run: cd actions && bash ./gradlew run -P JOB=GenerateMarkdownTable
