name: Repository Dispatch
on:
  repository_dispatch:
    types: [share]

jobs:
  share:
    runs-on: ubuntu-latest
    steps:
      # Clone and setup local repository
      - uses: actions/checkout@v1

      # Setup NodeJS
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      # Setup Dart SDK
      - uses: dart-lang/setup-dart@v1

      - name: Install Dart Packges
        run: cd actions && dart pub get

      - name: Open Issue Job
        env:
          USER_TOKEN: ${{ github.event.client_payload.token }}
          GITHUB_REPO_TOKEN: ${{ github.token }}
          REPOSITORY: ${{ github.repository }}
        run: cd actions && dart run lib/open_issue.dart
