name: Open Pool Issue
on:
  repository_dispatch:
    types: [open-issue]

jobs:
  open-issue:
    runs-on: ubuntu-latest
    steps:
      # Clone and setup local repository
      - uses: actions/checkout@v1

      # Setup Java
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "8"

      # Setup NodeJS
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      # Create a pool issue based on the auth user
      - name: Open Issue Job
        env:
          USER_TOKEN: ${{ github.event.client_payload.token }}
          GITHUB_REPO_TOKEN: ${{ secrets.GITHUB_REPO_TOKEN }}
          REPOSITORY: ${{ github.repository }}
        run: cd actions && bash ./gradlew run -P JOB=OpenIssue
